/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;

/**
 *
 * @author Marleny Pena Tvarez
 */
public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
        
        //establecer icono de la ventana
        this.setIconImage(new ImageIcon(getClass().getResource("/skyblue/Botones/SkyBlueIcon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        telefonoTXT = new javax.swing.JTextField();
        nombreUsuaioTXT = new javax.swing.JTextField();
        crearCuentaBTN = new javax.swing.JButton();
        cancelarBTN = new javax.swing.JButton();
        passwordConfirm = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        emailTXT = new javax.swing.JTextField();
        ciudadCB = new javax.swing.JComboBox();
        paisCB = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        apellidoTXT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fechaNacDC = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        direccionTXT = new javax.swing.JTextField();
        nombreTXT = new javax.swing.JTextField();
        TNumero = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TFVencimiento = new com.toedter.calendar.JDateChooser();
        TCodigo = new javax.swing.JTextField();
        TTramitada = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Femenino = new javax.swing.JRadioButton();
        Masculino = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        cedulaTXT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkyBlue - Crear cuenta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ciudad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/minilogo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 226, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nombre de Usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Confirmar contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));
        getContentPane().add(telefonoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 204, 25));
        getContentPane().add(nombreUsuaioTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 204, 25));

        crearCuentaBTN.setText("Crear Cuenta");
        getContentPane().add(crearCuentaBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 119, 31));

        cancelarBTN.setText("Cancelar");
        cancelarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 119, 31));
        getContentPane().add(passwordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 204, 25));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 204, 25));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/Registrate.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));
        getContentPane().add(emailTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 204, 25));

        getContentPane().add(ciudadCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 120, -1));

        paisCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisCBActionPerformed(evt);
            }
        });
        getContentPane().add(paisCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 130, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Direccion");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));
        getContentPane().add(apellidoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 204, 25));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Telefono");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Pais");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Apellido");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        fechaNacDC.setDateFormatString("yyyy-MM-dd");
        fechaNacDC.setOpaque(false);
        getContentPane().add(fechaNacDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 140, 25));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Email");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));
        getContentPane().add(direccionTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 204, 25));
        getContentPane().add(nombreTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 204, 25));
        getContentPane().add(TNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 160, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Fecha de vencimiento");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        TFVencimiento.setOpaque(false);
        getContentPane().add(TFVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 160, -1));
        getContentPane().add(TCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 50, -1));

        getContentPane().add(TTramitada, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 90, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("CVV");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Tramitada por:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Numero de Tarjeta de credito");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        Femenino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Femenino.setText("Fememino");
        Femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemeninoActionPerformed(evt);
            }
        });
        getContentPane().add(Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        Masculino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Masculino.setText("Masculino");
        getContentPane().add(Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Sexo:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));
        getContentPane().add(cedulaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 110, 25));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Cedula");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/images.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 820, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarBTNActionPerformed

    private void FemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemeninoActionPerformed

    private void paisCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisCBActionPerformed

    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   /*     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
  /*      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Femenino;
    public javax.swing.JRadioButton Masculino;
    public javax.swing.JTextField TCodigo;
    public com.toedter.calendar.JDateChooser TFVencimiento;
    public javax.swing.JTextField TNumero;
    public javax.swing.JComboBox TTramitada;
    public javax.swing.JTextField apellidoTXT;
    public javax.swing.JButton cancelarBTN;
    public javax.swing.JTextField cedulaTXT;
    public javax.swing.JComboBox ciudadCB;
    public javax.swing.JButton crearCuentaBTN;
    public javax.swing.JTextField direccionTXT;
    public javax.swing.JTextField emailTXT;
    public com.toedter.calendar.JDateChooser fechaNacDC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField nombreTXT;
    public javax.swing.JTextField nombreUsuaioTXT;
    public javax.swing.JComboBox paisCB;
    public javax.swing.JPasswordField password;
    public javax.swing.JPasswordField passwordConfirm;
    public javax.swing.JTextField telefonoTXT;
    // End of variables declaration//GEN-END:variables
}
