/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skyblue.View;

import javax.swing.ImageIcon;

/**
 *
 * @author Hector Castillo
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        //establecer icono
        this.setIconImage(new ImageIcon(getClass().getResource("/skyblue/Botones/SkyBlueIcon.png")).getImage());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        nombreUsuarioTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        iniciarSesionBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        claveOlvidadaLBL = new javax.swing.JLabel();
        crearCuentaBTN = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkyBlue - Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nombre de Usuario");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 200, -1));

        nombreUsuarioTXT.setBorder(null);
        getContentPane().add(nombreUsuarioTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 200, 22));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/TituloSkyBlue.png"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 297, -1));

        iniciarSesionBTN.setText("Iniciar Sesion");
        iniciarSesionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionBTNActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarSesionBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 200, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/Usuario.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 30, 42));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/Lock.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 30, -1));

        claveOlvidadaLBL.setText("Olvide mi contraseña");
        getContentPane().add(claveOlvidadaLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 120, 30));

        crearCuentaBTN.setAction(crearCuentaBTN.getAction());
        crearCuentaBTN.setForeground(new java.awt.Color(51, 51, 51));
        crearCuentaBTN.setText("Crear cuenta");
        crearCuentaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaBTNActionPerformed(evt);
            }
        });
        getContentPane().add(crearCuentaBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 120, 30));

        password.setBorder(null);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 200, 22));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/telegram04.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarSesionBTNActionPerformed

    private void crearCuentaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCuentaBTNActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                System.out.println("antes de login");
                new Login().setVisible(true);
                
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel claveOlvidadaLBL;
    public javax.swing.JButton crearCuentaBTN;
    public javax.swing.JButton iniciarSesionBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField nombreUsuarioTXT;
    public javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
