/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skyblue.View;

import javax.swing.ImageIcon;

/**
 *
 * @author Marleny Pena Tvarez
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/skyblue/Botones/SkyBlueIcon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        idUsuarioLBL = new javax.swing.JLabel();
        cerrarSesionBTN = new javax.swing.JButton();
        paisLBL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ReservacionesBTN = new javax.swing.JButton();
        ComprasBTN = new javax.swing.JButton();
        ItinierarioBTN = new javax.swing.JButton();
        BuscarVueloBTN = new javax.swing.JButton();
        MuestraContenido = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        ConfiguracionBTN = new javax.swing.JButton();
        nombreLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkyBlue");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/User.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 24, -1, 90));

        idUsuarioLBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idUsuarioLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idUsuarioLBL.setText("KatherineGP");
        getContentPane().add(idUsuarioLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 140, -1));

        cerrarSesionBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/cerrarSesion.png"))); // NOI18N
        cerrarSesionBTN.setText("Cerrar Sesion   ");
        cerrarSesionBTN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cerrarSesionBTN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        cerrarSesionBTN.setIconTextGap(35);
        getContentPane().add(cerrarSesionBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 217, 48));

        paisLBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paisLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paisLBL.setText("Republica Dominicana");
        getContentPane().add(paisLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/minilogo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 39, -1, 102));

        ReservacionesBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/ReservacionesMini.png"))); // NOI18N
        ReservacionesBTN.setText("Reservaciones");
        ReservacionesBTN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ReservacionesBTN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ReservacionesBTN.setIconTextGap(30);
        getContentPane().add(ReservacionesBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 217, 49));

        ComprasBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/Compras.png"))); // NOI18N
        ComprasBTN.setText("Compras Realizadas");
        ComprasBTN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ComprasBTN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ComprasBTN.setIconTextGap(15);
        getContentPane().add(ComprasBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 217, 48));

        ItinierarioBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/CalendarioIt.png"))); // NOI18N
        ItinierarioBTN.setText("Itinerario");
        ItinierarioBTN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ItinierarioBTN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ItinierarioBTN.setIconTextGap(40);
        getContentPane().add(ItinierarioBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 217, 50));

        BuscarVueloBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/BuscarVueloMini.png"))); // NOI18N
        BuscarVueloBTN.setText("Buscar Vuelo");
        BuscarVueloBTN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BuscarVueloBTN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BuscarVueloBTN.setIconTextGap(20);
        getContentPane().add(BuscarVueloBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 220, 50));

        MuestraContenido.setOpaque(false);
        MuestraContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/BuscarVuelo.png"))); // NOI18N
        MuestraContenido.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 324, -1));

        jPanel1.setBackground(java.awt.Color.white);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Desde:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Destino A:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boston", "Canada", "Londres", "Paris", "Santo Domingo" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boston", "Canada", "Londres ", "Paris", "Santo Domingo" }));

        jTextField1.setText("dd/mm/yy");
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("dd/mm/yy");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Fecha de salida");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Fecha de regreso");

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Vuelo de Ida");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Vuelo de ida y vuelta");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Cantidad de boletos");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        MuestraContenido.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        getContentPane().add(MuestraContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 660, 460));

        ConfiguracionBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/ConfiguracionMini.png"))); // NOI18N
        ConfiguracionBTN.setText("Configuracion");
        ConfiguracionBTN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ConfiguracionBTN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ConfiguracionBTN.setIconTextGap(35);
        getContentPane().add(ConfiguracionBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 217, 48));

        nombreLBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombreLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreLBL.setText("Marleny Pena");
        getContentPane().add(nombreLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyblue/Botones/images.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
 /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
     /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BuscarVueloBTN;
    public javax.swing.JButton ComprasBTN;
    public javax.swing.JButton ConfiguracionBTN;
    public javax.swing.JButton ItinierarioBTN;
    public javax.swing.JPanel MuestraContenido;
    public javax.swing.JButton ReservacionesBTN;
    public javax.swing.JButton cerrarSesionBTN;
    public javax.swing.JLabel idUsuarioLBL;
    public javax.swing.JButton jButton4;
    public javax.swing.JComboBox jComboBox1;
    public javax.swing.JComboBox jComboBox2;
    public javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JLabel nombreLBL;
    public javax.swing.JLabel paisLBL;
    // End of variables declaration//GEN-END:variables
}
