/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marleny Pena Tavarez
 */
public class ResultadosBusqueda extends javax.swing.JPanel {

    /**
     * Creates new form ResultadosBusqueda
     */
    public ResultadosBusqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResTable = new javax.swing.JTable();
        ComprarBTN = new javax.swing.JButton();
        CancelarBTN = new javax.swing.JButton();
        ReservarBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TotalLBL = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(680, 410));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/ResultadosBusqueda.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 424, -1));

        ResTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Aerolinea", "Origen", "Destino", "Fecha", "Hora", "Clase", "precio"
            }
        ));
        ResTable.setShowHorizontalLines(false);
        ResTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(ResTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 600, 290));

        ComprarBTN.setText("Comprar");
        ComprarBTN.setToolTipText("");
        add(ComprarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 168, 32));

        CancelarBTN.setText("Cancelar");
        CancelarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBTNActionPerformed(evt);
            }
        });
        add(CancelarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 170, 32));

        ReservarBTN.setText("Reservar");
        ReservarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarBTNActionPerformed(evt);
            }
        });
        add(ReservarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 170, 32));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Total:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        TotalLBL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(TotalLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 90, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarBTNActionPerformed

    private void ReservarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservarBTNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CancelarBTN;
    public javax.swing.JButton ComprarBTN;
    public javax.swing.JTable ResTable;
    public javax.swing.JButton ReservarBTN;
    public javax.swing.JLabel TotalLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    public DefaultTableModel model = new DefaultTableModel();
}
